TEMPLATE = lib
#QMAKE_POST_LINK = make install
#libs.files = ../apps/point_tracking_tools/bin/*.exe
#libs.path = $$PWD/../bin
#INSTALLS +=libs
OPENCV_DLL_DIR = $$PWD/../modules/opencv_1.0/bin
DEST_BIN_DIR = $$PWD/../bin
QMAKE_POST_LINK += mkdir $$DEST_BIN_DIR &
QMAKE_POST_LINK += cp ../apps/point_tracking_tools/bin/*.exe $$DEST_BIN_DIR &
QMAKE_POST_LINK += cp $$OPENCV_DLL_DIR/*.dll $$DEST_BIN_DIR
